apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false

  - name: Zabbix
    uid: zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080/api_jsonrpc.php
    isDefault: true
    jsonData:
      username: $ZBX_GRAFANA_USER
      trends: true
      trendsFrom: "7d"
      cacheTTL: "1h"
    secureJsonData:
      password: $ZBX_GRAFANA_PASSWORD

  - name: Wazuh
    uid: wazuh
    type: grafana-opensearch-datasource
    access: proxy
    url: $WAZUH_INDEXER_URL
    jsonData:
      flavor: opensearch
      database: "wazuh-alerts-*"
      timeField: "@timestamp"
      tlsSkipVerify: true
    basicAuth: true
    basicAuthUser: $WAZUH_INDEXER_USER
    secureJsonData:
      basicAuthPassword: $WAZUH_INDEXER_PASSWORD
